### ISSUE TITLE
plugin doesn't work after newest melonloader update

### ISSUE THREAD

**Issue by DellConagher** [Huntereb/Force-Clone#2]
![y2k25Pt7p0](https://user-images.githubusercontent.com/7874388/92779562-27edbd00-f370-11ea-9be4-fa6cac5cffbd.png)

The button appears on the menu, but clicking the button doesn't do anything.

**Comment by SphereII** [comment]
try using a differernt mod launcher i have the same problem

**Comment by Huntereb** [comment]
I just keep forgetting to update this on github, sorry.
